clear;
clc;
close all;

% Find the folder containing this MATLAB script.
scriptPath = mfilename("fullpath");
analysisFolder = fileparts(scriptPath);

% Move one folder upward to the lap_recorder project folder.
projectFolder = fileparts(analysisFolder);

% Build the complete path to the CSV generated by C++.
csvPath = fullfile(projectFolder, "data", "saved_laps.csv");

% Stop safely if the CSV does not exist.
if ~isfile(csvPath)
    error("CSV file not found: %s", csvPath);
end

% Read the CSV into a MATLAB table.
laps = readtable(csvPath);

if isempty(laps)
    error("The CSV contains no lap data.");
end

% Plot lap time against lap number.
figure;

plot(laps.lapNumber, laps.lapTime, "-o", "LineWidth", 1.5);

xlabel("Lap number");
ylabel("Lap time (seconds)");
title("Lap Time by Lap");
grid on;

%photo of the graph
imagePath = fullfile(projectFolder, "data", "lap_times.png");
exportgraphics(gcf, imagePath, "Resolution", 300);

%edit the graph
figurePath = fullfile(projectFolder, "data", "lap_times.fig");
savefig(gcf, figurePath);

fprintf("Figure saved to: %s\n", imagePath);
fprintf("MATLAB figure saved to: %s\n", figurePath);

% Calculate statistics.
[minTime, row] = min(laps.lapTime);

fastestLap = laps.lapNumber(row);
averageTime = mean(laps.lapTime);

% Print statistics in the MATLAB terminal.
fprintf("Fastest lap: %.0f\n", fastestLap);
fprintf("Fastest time: %.2f seconds\n", minTime);
fprintf("Average time: %.2f seconds\n", averageTime);